### ISSUE TITLE
OpenSplice update

### ISSUE THREAD

**Issue by michielb-prismtech** [ros2/rmw_opensplice#187]
We've made some updates to the OpenSplice 6.7 Community Edition (https://github.com/PrismTech/opensplice/commits/master)
This update should significantly decrease the number of failing testcases. Solved issues:
- unable to create reader for topic starting with '_'
- delete_contained_entities failed because of outstanding loans in listener callback
- deadlock when calling guard_condition_trigger when adding/removing guard condition from/to waitset

Can someone kick off a new build and test run with the latest OpenSplice version?

**Comment by dirk-thomas** [comment]
I created a new Debian package (`libopensplice67_6.7.0+osrf2-2` in http://packages.osrfoundation.org/gazebo/ubuntu/pool/main/libo/libopensplice67/) and ran a new build using it: [![Build Status](http://ci.ros2.org/buildStatus/icon?job=ci_linux&build=3095)](http://ci.ros2.org/job/ci_linux/3095/)

**Comment by michielb-prismtech** [comment]
What are those projectroot failures? They seem like duplicates of tests further down the list

**Comment by dirk-thomas** [comment]
Yes, many test results get reported twice - once by `nosetests` / `gtest` and another time by `CTest`. Both reports have different advantages. That is why we use both atm.

**Comment by michielb-prismtech** [comment]
Pretty happy with last nights results. We're down to 10 failures and 6 unique ones. From those 6 three are unsolvable (copyright and cpplint) as the files are correct (Can someone concession those?). For the other 3 fails two are because of an unimplemented function and the other because it's expecting something which is not part of the DDS spec. For those we are working on a solution.

**Comment by mikaelarguedas** [comment]
> We're down to 10 failures and 6 unique ones.

great news!

Regarding the copyright failure you are right the file is correct, this is due to the current limitation of the copyright checker itself (partially addressed by https://github.com/ament/ament_lint/pull/82). I don't think there is a way to disable the test for only one specific file. I made a version that passes the test [here](https://github.com/ros2/rmw_opensplice/pull/188), could you have a look at it and see if this would be acceptable ?

Regarding the cpplint error, the error is genuine given thet the include style doesnt follow our style guide. 
I guess respecting our style is not possible because the files are not located in include directories in the opensplice file tree? If they are you should be able to include them following the format `#include "PKG_NAME/myfile.h", if they are not you can skip the linter test for specific lines (see https://github.com/ros2/rmw_opensplice/pull/189 for an example of how to do so)
